
#include <jsonrpc/rpc.h>
#include <iostream>

//Include client interface generated by tooling
#include "rpcstubclient.h"

using namespace jsonrpc;
using namespace std;

int main()
{
    RPCStubClient c(new HttpClient("http://localhost:8080"));

    try
    {
				std::string response = c.ShowMessage("DisplayOne", "Hello world...", 100, 100);
        cout<<"Server response to ShowMessage call: "<<response<<endl;
    }
    catch (JsonRpcException e)
    {
        cerr << e.what() << endl;
    }


}

