
#include <jsonrpc/rpc.h>
#include <iostream>
#include <string>

//Include client interface generated by tooling
#include "rpcstubclient.h"

using namespace jsonrpc;
using namespace std;

int main(int argc, char* argv[])
{
    RPCStubClient c(new HttpClient("http://localhost:8080"));

	std::string blurb = "Hello World...";
	if(argc>1) {
		blurb = argv[1];
	}

    try
    {
				std::string response = c.ShowMessage("DisplayOne", blurb, 100, 100);
        cout<<"Server response to ShowMessage call: "<<response<<endl;
    }
    catch (JsonRpcException e)
    {
        cerr << e.what() << endl;
    }


}

